name: makesh_vineeth
description: Portfolio.

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^2.2.0
  animated_text_kit: ^4.2.1
  flutter_fadein: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  octo_image: ^1.0.0+1
  responsive_framework: ^0.1.2
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "mv_icon"
  image_path: "assets/mv_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
