name: makesh_vineeth
description: Portfolio

publish_to: "none" 
version: 2.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  flutter_fadein: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  octo_image: ^1.0.2
  responsive_framework: ^1.0.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "mv_icon"
  image_path: "assets/mv_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
